import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    fondo:{
        flex:1,
        backgroundColor:'black',
        paddingHorizontal:0
    },
    calculadoraContainer:{
        flex:1,
        justifyContent:'flex-end',
        paddingHorizontal:20
    },
    resultado:{
        color:'white',
        fontSize:60,
        textAlign:'right',
    },
    resultadoSmall:{
        color:'rgba(225,225,225,0.5)', 
        fontSize:20,
        textAlign:'right',
    },
    fila:{
        flexDirection:'row',
        justifyContent:'center'
    },
    button:{
        height:80,
        width:80,
        backgroundColor:'#9B9B9B',
        borderRadius:100,
        justifyContent:'center'
    },
    buttonText:{
        textAlign:'center',
        padding:10,
        fontSize:30,
        color:'white',
        fontWeight:'300'
    }
});